remote_theme: pmarsceill/just-the-docs

aux_links:
  "Spark Rapids Plugin on Github":
    - "//github.com/nvidia/spark-rapids"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
